### ISSUE TITLE
missing documentation for secure-websockets

### ISSUE THREAD

**Issue by bchase78** [m-lab/ndt#47]
There is code implementing secure-websockt communication. 

Our goal is to enable secure-websockets and do some performance testing.

I have created a valid Webserver certificate, but I do not know how to configure it for use with the ndt server.  I was not able to find any documentaion of this.

What are the steps necessary to configure ndt with secure-websockets?

**Comment by pboothe** [comment]
Where would you like this documentation to live? In INSTALL? In README?  The short version is that you need three arguments to pass three arguments to `web100srv` to get secure testing working: `--tls_port`, `--certificate`, and `--private_key`

**Comment by bchase78** [comment]
Thanks. That is what I was looking for. I guess I was a little blind not seeing that in the sources.

As far as Documentation goes, I personally don't have any requirements as, I have worked my way through most of the material.  But that being said, the current Documentation from Internet2 is somewhat dated.  There is a steep learning curve for someone getting started with NDT for the first time and current Documentation would probably help.
