### ISSUE TITLE
client_application field populated with large hex values

### ISSUE THREAD

**Issue by gfr10598** [m-lab/ndt#74]
From Jan 2016 through April 2016, a modest number of ndt tests (~10 thousand) have 8 byte hex values in the client field.  Do we know why?
https://bigquery.cloud.google.com/results/api-appsbackup-pa:bquijob_4ba73efd_158d4a51fe3?pli=1

**Comment by pboothe** [comment]
The client field is freeform text submitted by the user. It could be being used as a foreign key into a database we don't know about.  I know that something like this was done for the "measuring schools" project that OTI did.

**Comment by critzo** [comment]
Sorry I hadn't seen this thread sooner, but I can confirm that Peter's
suspicion is correct. We used this field for our school analysis pilot. The
random field was generated and stored client side and then used to query
the database later to associate test originating from specific clients. It
worked quite well from my perspective. This was using the ndt c client.
